### ISSUE TITLE
undefined method `create_transaction'

### ISSUE THREAD

**Issue by Jecko-o** [mollie/spree-mollie-gateway#12]
Using mollie along with the spree native check payment method I'm getting the following error:

> "NoMethodError in Spree::CheckoutController#update 
>  undefined method `create_transaction' for #<Spree::PaymentMethod::Check:0x00007f143a532910>"

It seems a problem in mollie [processing_decorator](https://github.com/mollie/spree-mollie-gateway/blob/master/app/models/spree/payment/processing_decorator.rb) override of the _process!_ method.

**Comment by vernondegoede** [comment]
Thanks for reporting @Jecko-o! [This has been fixed](https://github.com/mollie/spree-mollie-gateway/releases/tag/1.0.6) in `1.0.6`.

Let me know if you experience any other issues.

**Comment by Jecko-o** [comment]
Ok! :smile:
