### ISSUE TITLE
undefined method `issuers' for #<Mollie::Method:0x007fc3417f17d0>

### ISSUE THREAD

**Issue by MatthewKennedy** [mollie/spree-mollie-gateway#3]
Using a fresh install I get the following error when going to checkout payment 

undefined method `issuers' for #<Mollie::Method:0x007fc3417f17d0>

**Comment by vernondegoede** [comment]
Thanks @MatthewKennedy.

Once https://github.com/mollie/mollie-api-ruby version 3.1.4 has been released (probably later today), this issue will be resolved.

**Comment by vernondegoede** [comment]
Fixed in version 1.0.2: https://rubygems.org/gems/spree_mollie_gateway/versions/1.0.2
