### ISSUE TITLE
Mollie returns payment state 'created' which is unhandled by the gem

### ISSUE THREAD

**Issue by Oldharlem** [mollie/spree-mollie-gateway#45]
Mollie returns payment state creared upon creating a mollie payment. This state is unhandled and will reset the order to state payment and remove the completed_at timestamp. 

In our system we have dozens of orders that are still in state payment with a stateless payment. Webhooks did not come in while the order on the mollie side is paid and even paid out. 

`D, [2018-11-26T15:20:58.010696 #25594] DEBUG -- : Unhandled Mollie payment state received: created. Therefore we did not update the payment state.`

**Comment by vernondegoede** [comment]
Thanks. Released in 3.0.2 🚀
