### ISSUE TITLE
Multiple refunds not permitted

### ISSUE THREAD

**Issue by Oldharlem** [mollie/spree-mollie-gateway#47]
When creating multiple return authorisations, multiple customer returns can be created. For each return a refund reimbursement option is allowed. Unfortunately only the first reimbursement can be refunded, all later refund reimbursements are blocked by mollie

**Comment by vernondegoede** [comment]
Currently orders cannot be refunded within the Spree Mollie gateway: #40

**Comment by Oldharlem** [comment]
PR #61 fixes this

**Comment by Oldharlem** [comment]
This is part of #40
