### ISSUE TITLE
/admin/orders index crash

### ISSUE THREAD

**Issue by sekretarot** [mollie/spree-mollie-gateway#51]
Installing the spree_mollie_gateway 3.0.3 version breaks the orders index page in the backend on new spree install on version 3.1.x. 
We get a method missing error on store_id_in. Please see screenshots and let me know if you need more info. 

![screen shot 2018-12-03 at 2 13 51 pm](https://user-images.githubusercontent.com/5826738/49376093-6fa8d480-f706-11e8-8f57-8047f73518dc.png)

![screen shot 2018-12-03 at 1 50 40 pm](https://user-images.githubusercontent.com/5826738/49376108-7899a600-f706-11e8-8780-730dbc376009.png)

**Comment by vernondegoede** [comment]
Hi @sekretarot, the minimum Spree version is 3.3.x, since the gateway depends on the `Spree::InventoryUnits` model.

**Comment by sekretarot** [comment]
Hi @vernondegoede  

Ok, fair enough. We will look into a way to fix it. 

But are you guys sure that this also works with version 3.3? 

The issue is because the view assumes that the "store" relation on the order model is ransackable. 

This got added to spree in [this commit](https://github.com/spree/spree/commit/39e1e3de56b1f16766a7e4007f4b70788f6dfad3) which was added starting from 3.5.0rc.  

Maybe I'm missing something but if this is the case you might want to raise the spree dependency to 3.5 or maybe we can add this to the gem if you are willing to support older versions. 

I can add a PR for this but I am not sure how you guys want to approach this.

**Comment by vernondegoede** [comment]
Sorry @sekretarot. You're right. The minimum Spree version should be 3.5.x instead of 3.3.x.
