### ISSUE TITLE
Check compatibility with 3.7.0.rc1

### ISSUE THREAD

**Issue by vernondegoede** [mollie/spree-mollie-gateway#56]
The first release candidate for Spree 3.7.0 was just released, which introduced the V2 API and a new dependency system.

https://github.com/spree/spree/releases/tag/v3.7.0.rc1

**Comment by soast** [comment]
Hi, just checking in, judging from #59 and #60 is this library still maintained?

**Comment by Oldharlem** [comment]
> Hi, just checking in, judging from #59 and #60 is this library still maintained?

Yes very well so :)

**Comment by Oldharlem** [comment]
Since we cannot find any direct issues with spree 3.7 this general issue will be closed.
