### ISSUE TITLE
Mollie not compatible with Spree 3.7

### ISSUE THREAD

**Issue by salman15** [mollie/spree-mollie-gateway#59]
I've installed the latest version of Spree on a clean installation of Ruby on Rails 5.2 

and get the following error when viewing "admin/orders"

![image](https://user-images.githubusercontent.com/24669227/54520390-ea6dc680-4968-11e9-8edb-462602d516eb.png)

**Comment by Oldharlem** [comment]
@salman15 could you please provide steps to reproduce the issue?

**Comment by Oldharlem** [comment]
We are waiting on your reply in order to fix this issue

**Comment by Oldharlem** [comment]
@salman15 could you let us know if this is resolved now or more help is required? Otherwise we will close the issue

**Comment by dbbooke12** [comment]
I also get this message on installing a fresh spree 3.7.3 rails 5.2.3 and ruby 2.5.1.

Is there any update on this?
