### ISSUE TITLE
Bug with spree 3.7 and latest spree-mollie-gateway

### ISSUE THREAD

**Issue by salman15** [mollie/spree-mollie-gateway#60]
When trying to order a product I get this error with only this gateway

![image](https://user-images.githubusercontent.com/24669227/54596174-64b74d00-4a34-11e9-8035-840ef6399fd3.png)

**Comment by Oldharlem** [comment]
@salman15 could you provide some more information? This issue seems to derive from a missing country on your shipping address which is mandatory for the mollie gateway. 

Can you send the address provided and full stack trace?

**Comment by Oldharlem** [comment]
We are waiting on your reply in order to fix this issue

**Comment by Oldharlem** [comment]
@salman15 could you let us know if this is resolved now or more help is required? Otherwise we will close the issue
