### ISSUE TITLE
Add P24 payment method

### ISSUE THREAD

**Issue by vernondegoede** [mollie/spree-mollie-gateway#67]
Mollie recently added the payment method [Przelewy24](https://www.mollie.com/en/payments/przelewy24) (P24).

We want this payment method to show up as the used payment method when payment details are checked through the Spree admin. Check out for more information: https://github.com/mollie/spree-mollie-gateway/blob/master/app/models/spree/mollie_payment_source.rb

**Comment by Oldharlem** [comment]
PR #71 resolves this
