### ISSUE TITLE
No payment options

### ISSUE THREAD

**Issue by salman15** [mollie/spree-mollie-gateway#68]
I've installed spree with the seed data and spree_mollie_gateway gem. When I get to the payment screen in the checkout and select my mollie payment I don't get any of the payment options. 

I've set up the mollie gateway correctly, as I've done in the past. 

It's pretty frustrating that both version 3.6 and 3.7 of spree aren't compatible with this gem. 

I'm running :
Ruby 2.4, 
gem 'rails' , '5.2.0, '
gem 'spree', '3.6.0'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '3.3'
gem 'spree_mollie_gateway', '3.0'

**Comment by Oldharlem** [comment]
@salman15 I've tested both spree versions and they seem to work correctly.

There could be multiple sources for your problems:

Mollie determines the available gateways based on the currency and origin country of the order.
See the [available_methods_for_order](https://github.com/mollie/spree-mollie-gateway/blob/master/app/models/spree/gateway/mollie_gateway.rb#L135) method. 
If the address' country or order currency does not match any payment methods the list will be empty.

There could be a problem with your website profile. If your website profile has not been (fully) approved this may affect the available payment methods.

Please let me know if you need more help on this.

**Comment by Oldharlem** [comment]
We are waiting on your reply in order to fix this issue

**Comment by Oldharlem** [comment]
@salman15 could you let us know if this is resolved now or more help is required?

**Comment by dbbooke12** [comment]
I am getting the same results. Gateway set up correctly and currency and country matches. Profile is completely set up. Not sure what this can be.
