### ISSUE TITLE
Outdated documentation missing 'Auto Capture'

### ISSUE THREAD

**Issue by DianaKoenraadt** [mollie/spree-mollie-gateway#87]
What is the recommended value for Auto Capture?

![image](https://user-images.githubusercontent.com/5881327/77166234-28d61e00-6ab4-11ea-9592-2d09c42e8f92.png)

I'm not entirely sure but if we set it to false, I believe we need to do manual actions. Could you perhaps also clarify what these manual actions consist of?

**Comment by Oldharlem** [comment]
Hi @DianaKoenraadt 

The auto capture option on the payment method is ignored and originates from the spree implementation of active merchant. 
In the [mollie_gateway.rb:39](https://github.com/mollie/spree-mollie-gateway/blob/321e157edc41d88cab1e5fb993bea292c9f8889d/app/models/spree/gateway/mollie_gateway.rb#L39) you'll find the auto_capture option is fixed to true. 


By default the mollie gem is configured to `auto_capture_on_dispatch` which means on dispatch of a shipment the payments associated to the package contents are auto captured. 

Capturing for most payment gateways is meaningless. Although for example after pay payments require a capture event to retrieve the funds.  The `auto_capture_on_dispatch` setting takes care of this automatically and I would advice against disabling this and manually capturing payments where possible.

**Comment by DianaKoenraadt** [comment]
Thanks for your reply. So, if I understand correctly:

- Capture is the action Mollie does after the customer has said "Sure, I'll pay" (=authorization). Capturing is the _actual money withdrawal_, right?
- In most payment methods, there is no difference between authorization and withdrawal. But as I understand, for Credit Cards, you need capture.
- And you guys have set auto-capture to true in your plugin, so that the webshop don't have to do it manually. If the customer authorizes, you capture automatically.
- But you don't do this until the package is **shipped**?

Is that the correct summary?

**Comment by Oldharlem** [comment]
You are mostly right.

The capture is being executed on dispatch of the shipment, so when you click ship in the spree backend for example.

**Comment by DianaKoenraadt** [comment]
Thank you for your reply, much appreciated.

Feels like that's what I said: we click that we've shipped the package and then the payment is captured. Am I missing a detail in my understanding? (Note: We've just started digging through Spree so I'm not well versed yet.)

Could you perhaps clarify why the capture isn't done immediately? Is this a technical or legal decision?

**Comment by Oldharlem** [comment]
From your explanation i thought i understood you were asking when the capture event is triggered. This is done at shipment.

As far as i know only creditcards and after pay payments are legally required to be shipped before they can be captured.

Maybe @vernon can elaborate more on the specific capture rules per payment gateway.

**Comment by DianaKoenraadt** [comment]
Thanks, that clears it up for me! 
I knew about after pay like Klarna. Didn't know the same held for credit cards. My initial question is answered, I understand the Auto Capture function now. Thanks!

**Comment by Oldharlem** [comment]
Happy to help :)
