### ISSUE TITLE
Mollie gateway doesn't work on local

### ISSUE THREAD

**Issue by oamado** [mollie/spree-mollie-gateway#91]
I'm trying to test the gateway but it doesn't work.
![image](https://user-images.githubusercontent.com/3857305/87492428-29b92f80-c610-11ea-99b9-448b36df7135.png)
When I click on purchase I got this message: **Payments source can't be blank**

![image](https://user-images.githubusercontent.com/3857305/87492526-540aed00-c610-11ea-8320-f6d67f59146c.png)
I'm using a a test token and running with data example from spree
Here is a repo with my setup https://github.com/encaja-digital/mollie_test

**Comment by vernondegoede** [comment]
@Oldharlem Could you take a look?

**Comment by Oldharlem** [comment]
Hi @oamado 

I am sorry you are experiencing difficulties. 
By the looks of things it seems like there are not active gateways. Can you check your mollie dashboard and see if there are any payment methods enabled under settings > website profiles > payment methods for the specific website profile api key you are using. 

If that all looks correct we will dive deeper.

**Comment by oamado** [comment]
Hi @Oldharlem Thanks for the reply, It was the solution!! :) I haven't set any payment method in the mollie dashboard
